# Site settings
title: Optimización de Código
email:
description: > # this means to ignore newlines until "baseurl:"
  Sitio dedicado a la recopilación de las mejores prácticas y estandares
  de programación.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:3000" # the base hostname & protocol for your site
exclude: [Gemfile, Gemfile.lock, Procfile]
encoding: utf-8
sites:
    php:
        title: "PHP"

last_version: 1.0


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
